######################################################################
##
## Filename: afe_tb.udo
## Created on: Mon Feb 06 14:28:30 W. Europe Standard Time 2023
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
